version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=mongodb://nikhil:nikhil987@13.61.141.31:5002/url-shortener?authSource=admin&readPreference=primary&ssl=false
      - PORT=5003
      - BASE_URL=http://13.60.183.216:4003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "4002:4002"
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
